package constant

type OtaProgram string

const (
	PROGRAM_APP OtaProgram = "aro-app"
)

const (
	BACKEND_ENCODE_PUBLIC_KEY = "LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJDZ0tDQVFFQTBocFFjTng5NEk5TGNvUFpzMlJRRktLa2tiaXZFOEhtd3NGaXVYRTFtdFpMRGcwRUlUVWoKRzVLUXRUUjgzZGhyWG5lLzB5TkhxdVNacWZIcnpLM2YrUE8wbmllNmlROFl0UlZVWW5INjRzUXBuYld6V2ZhbgpFT0RMSVNwUThZS1pzZSt4SVorTzZFaUduUGFnZStBWnZnQmJhcjltb3Z4L3ZXcmVzWDVRellTOGlaZ3FFNGoyClFYVE5CYnFqa0NEZFpoT1NVelAxckw0dSt3UEdBMW16RU5laDI1Sk5OQUlkNG90VVpvSHlMZFdHMWlFVFhvM0sKcy9Kb0tQZ3YrTVVLWDFuQm5ubHhTMnoxTDMvS0QxK3dqeTNhSDBrbVQvYWFmTFFrbk8xcHlJcjhZQWZpZGVkNgpNRklGa3lnTlJkYVkyU0J2VGlVeG93UnBwa0RKdzZqWll3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K"
	HTTP_SERVER_ENDPOINT      = "https://staging-api.aro.network"
	WS_SERVER_ENDPOINT        = "staging-ws.aro.network"
	ENV                       = "dev"
)
