; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ARO"
#define MyAppVersion "0.0.1"
#define MyAppPublisher "ARO Network"
#define MyAppURL "https://aro.network"
#define MyAppExeName "aro_desktop.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E6390888-0010-4820-9786-0C7A14897099}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
; Allow user to select the installation directory (User Request 1)
DisableDirPage=no
; Create a Start Menu folder (User Request 2)
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
OutputDir=.\Output
OutputBaseFilename=ARO_Setup
SetupIconFile=..\runner\resources\app_icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
; Ensure uninstall info is registered (User Request 3)
UninstallDisplayIcon={app}\{#MyAppExeName}
; Prevent install/uninstall while the app is running
AppMutex=AROClientMutex

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a desktop icon"; Flags: unchecked

[Files]
; NOTE: Verify the build path. For newer Flutter versions (3.10+), it is often build\windows\x64\runner\Release
; If your build is in build\windows\runner\Release, adjust the path below.
Source: "..\..\build\windows\x64\runner\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Ensure tray icon exists at {app}\resources\app_icon.ico
Source: "..\runner\resources\app_icon.ico"; DestDir: "{app}\resources"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
const
	ARO_MUTEX_NAME = 'AROClientMutex';

function OpenMutex(dwDesiredAccess: LongWord; bInheritHandle: Boolean; lpName: string): LongWord;
	external 'OpenMutexW@kernel32.dll stdcall';
function CloseHandle(hObject: LongWord): Boolean;
	external 'CloseHandle@kernel32.dll stdcall';

function IsAroRunningByMutex(): Boolean;
var
	h: LongWord;
begin
	h := OpenMutex($001F0001, False, ARO_MUTEX_NAME);
	if h <> 0 then begin
		CloseHandle(h);
		Result := True;
	end else begin
		Result := False;
	end;
end;

function IsAroRunningByWindow(): Boolean;
begin
	Result := (FindWindowByWindowName('aro_desktop') <> 0);
end;

function InitializeUninstall(): Boolean;
begin
	if IsAroRunningByMutex() or IsAroRunningByWindow() then begin
		MsgBox(
			'ARO is currently running.'#13#10#13#10 +
			'Please exit the app first (tray menu -> Exit), then run uninstall again.',
			mbError, MB_OK);
		Result := False;
	end else begin
		Result := True;
	end;
end;
