; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ARO"
#define MyAppVersion "0.0.1"
#define MyAppPublisher "ARO Network"
#define MyAppURL "https://aro.network"
#define MyAppExeName "aro_desktop.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E6390888-0010-4820-9786-0C7A14897099}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
; Allow user to select the installation directory (User Request 1)
DisableDirPage=no
; Create a Start Menu folder (User Request 2)
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
OutputDir=.\Output
OutputBaseFilename=ARO_Setup
SetupIconFile=..\runner\resources\app_icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
; Ensure uninstall info is registered (User Request 3)
UninstallDisplayIcon={app}\{#MyAppExeName}
; Prevent install/uninstall while the app is running
AppMutex=AROClientMutex

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a desktop icon"; Flags: unchecked

[Files]
; NOTE: Verify the build path. For newer Flutter versions (3.10+), it is often build\windows\x64\runner\Release
; If your build is in build\windows\runner\Release, adjust the path below.
Source: "..\..\build\windows\x64\runner\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Ensure tray icon exists at {app}\resources\app_icon.ico
Source: "..\runner\resources\app_icon.ico"; DestDir: "{app}\resources"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

; Delete all related user data/config on uninstall
; NOTE: This intentionally removes configs/logs/state under common locations.
[UninstallDelete]
; Go config system locations
Type: filesandordirs; Name: "{userappdata}\ARO"
Type: filesandordirs; Name: "{localappdata}\ARO"
Type: filesandordirs; Name: "{userprofile}\.aro"

; libstudy logs (Go dylib)
Type: filesandordirs; Name: "{userappdata}\libstudy"

; Flutter/path_provider application support directories (best-effort)
; Most Flutter Windows builds use %APPDATA%\<exeBaseName> as support dir.
Type: filesandordirs; Name: "{userappdata}\aro_desktop"
Type: filesandordirs; Name: "{localappdata}\aro_desktop"

; Some setups nest under a vendor/company folder (from executable metadata)
Type: filesandordirs; Name: "{userappdata}\com.aro\aro_desktop"
Type: filesandordirs; Name: "{localappdata}\com.aro\aro_desktop"

; Backward/alternative names
Type: filesandordirs; Name: "{userappdata}\aro_client"
Type: filesandordirs; Name: "{localappdata}\aro_client"
Type: filesandordirs; Name: "{userappdata}\com.aro\aro_client"
Type: filesandordirs; Name: "{localappdata}\com.aro\aro_client"

; Remove vendor folder only if empty (avoid deleting other apps' data)
Type: dirifempty; Name: "{userappdata}\com.aro"
Type: dirifempty; Name: "{localappdata}\com.aro"

[Code]
const
	ARO_MUTEX_NAME = 'AROClientMutex';
	ARO_PROCESS_NAME = '{#MyAppExeName}';

function OpenMutex(dwDesiredAccess: LongWord; bInheritHandle: Boolean; lpName: string): LongWord;
	external 'OpenMutexW@kernel32.dll stdcall';
function CloseHandle(hObject: LongWord): Boolean;
	external 'CloseHandle@kernel32.dll stdcall';

function IsAroRunningByMutex(): Boolean;
var
	h: LongWord;
begin
	// Use minimal access to reduce permission-related false negatives.
	// SYNCHRONIZE = $00100000
	h := OpenMutex($00100000, False, ARO_MUTEX_NAME);
	if h <> 0 then begin
		CloseHandle(h);
		Result := True;
	end else begin
		Result := False;
	end;
end;

function IsAroRunningByWindow(): Boolean;
begin
	Result := (FindWindowByWindowName('ARO Desktop') <> 0);
end;

function IsAroRunningByProcess(): Boolean;
var
	ResultCode: Integer;
	OutFile: string;
	Cmd: string;
	Content: string;
begin
	Result := False;

	// Use tasklist as a robust fallback when mutex/window detection fails.
	OutFile := ExpandConstant('{tmp}\aro_tasklist.txt');
	DeleteFile(OutFile);
	Cmd := 'tasklist /FI "IMAGENAME eq ' + ARO_PROCESS_NAME + '" /NH > "' + OutFile + '"';
	if Exec('cmd.exe', '/c ' + Cmd, '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then begin
		if LoadStringFromFile(OutFile, Content) then begin
			Content := LowerCase(Content);
			Result := (Pos(LowerCase(ARO_PROCESS_NAME), Content) > 0);
		end;
	end;
end;

function InitializeUninstall(): Boolean;
begin
	if IsAroRunningByMutex() or IsAroRunningByWindow() or IsAroRunningByProcess() then begin
		MsgBox(
			'ARO is currently running.'#13#10#13#10 +
			'Please exit the app first (tray menu -> Exit), then run uninstall again.',
			mbError, MB_OK);
		Result := False;
	end else begin
		Result := True;
	end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
	// Extra safety: abort right before uninstall starts deleting files.
	if CurUninstallStep = usUninstall then begin
		if IsAroRunningByMutex() or IsAroRunningByWindow() or IsAroRunningByProcess() then begin
			MsgBox(
				'ARO is currently running.'#13#10#13#10 +
				'Please exit the app first (tray menu -> Exit), then run uninstall again.',
				mbError, MB_OK);
			Abort;
		end;
	end;
end;
